[server]
port = 8080
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = true
headless = true

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[theme]
primaryColor = "#E13427"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"